spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: postgres
    password: ENC(OYwKBj1pPp0V5NsRyMclq5+rJnqChUQ5T6W4W4NnC6k=)
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

decorator:
  datasource:
    p6spy:
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"

jwt:
  secret: ENC(DqCxj96IPCPwdi/EMW5uFhtGH3BzxS72i3gFxLlG7sOJ9vdpa6C5JbK/Ze/RqRsEaaedZLUbuvOWUirTlUxeHEczhnMvjEtKnBNgm/Cbu2rtRonzJKQAFw==)
